/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminJuridicoRouteImport } from './routes/_authenticated/admin.juridico'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminDocumentosRouteImport } from './routes/_authenticated/admin.documentos'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminAfiliadosRouteImport } from './routes/_authenticated/admin.afiliados'
import { Route as AuthenticatedAdminAfiliadosIdRouteImport } from './routes/_authenticated/admin.afiliados.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminJuridicoRoute =
  AuthenticatedAdminJuridicoRouteImport.update({
    id: '/juridico',
    path: '/juridico',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentosRoute =
  AuthenticatedAdminDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAfiliadosRoute =
  AuthenticatedAdminAfiliadosRouteImport.update({
    id: '/afiliados',
    path: '/afiliados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAfiliadosIdRoute =
  AuthenticatedAdminAfiliadosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminAfiliadosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/admin/afiliados': typeof AuthenticatedAdminAfiliadosRouteWithChildren
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/afiliados/$id': typeof AuthenticatedAdminAfiliadosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/admin/afiliados': typeof AuthenticatedAdminAfiliadosRouteWithChildren
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/afiliados/$id': typeof AuthenticatedAdminAfiliadosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/admin/afiliados': typeof AuthenticatedAdminAfiliadosRouteWithChildren
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/afiliados/$id': typeof AuthenticatedAdminAfiliadosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/admin/afiliados'
    | '/admin/configuracoes'
    | '/admin/documentos'
    | '/admin/financeiro'
    | '/admin/juridico'
    | '/admin/'
    | '/admin/afiliados/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/admin/afiliados'
    | '/admin/configuracoes'
    | '/admin/documentos'
    | '/admin/financeiro'
    | '/admin/juridico'
    | '/admin'
    | '/admin/afiliados/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/afiliados'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/documentos'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/juridico'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/afiliados/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/juridico': {
      id: '/_authenticated/admin/juridico'
      path: '/juridico'
      fullPath: '/admin/juridico'
      preLoaderRoute: typeof AuthenticatedAdminJuridicoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documentos': {
      id: '/_authenticated/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AuthenticatedAdminDocumentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/afiliados': {
      id: '/_authenticated/admin/afiliados'
      path: '/afiliados'
      fullPath: '/admin/afiliados'
      preLoaderRoute: typeof AuthenticatedAdminAfiliadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/afiliados/$id': {
      id: '/_authenticated/admin/afiliados/$id'
      path: '/$id'
      fullPath: '/admin/afiliados/$id'
      preLoaderRoute: typeof AuthenticatedAdminAfiliadosIdRouteImport
      parentRoute: typeof AuthenticatedAdminAfiliadosRoute
    }
  }
}

interface AuthenticatedAdminAfiliadosRouteChildren {
  AuthenticatedAdminAfiliadosIdRoute: typeof AuthenticatedAdminAfiliadosIdRoute
}

const AuthenticatedAdminAfiliadosRouteChildren: AuthenticatedAdminAfiliadosRouteChildren =
  {
    AuthenticatedAdminAfiliadosIdRoute: AuthenticatedAdminAfiliadosIdRoute,
  }

const AuthenticatedAdminAfiliadosRouteWithChildren =
  AuthenticatedAdminAfiliadosRoute._addFileChildren(
    AuthenticatedAdminAfiliadosRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAfiliadosRoute: typeof AuthenticatedAdminAfiliadosRouteWithChildren
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminDocumentosRoute: typeof AuthenticatedAdminDocumentosRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminJuridicoRoute: typeof AuthenticatedAdminJuridicoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAfiliadosRoute:
    AuthenticatedAdminAfiliadosRouteWithChildren,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminDocumentosRoute: AuthenticatedAdminDocumentosRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminJuridicoRoute: AuthenticatedAdminJuridicoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
